server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: movieapp-api

  datasource:
    url: jdbc:postgresql://localhost:5432/moviedb
    username: postgres
    password: postgres123

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
